"""Generated from the jfinance key mapping. Do not edit by hand."""

# ＋α の財務キー（Yahoo に同名が無いもの。企業）: キー → 説明
EXTRA_KEYS = {
    'OrdinaryIncome': '経常利益（日本基準）',
    'NonOperatingIncome': '営業外収益',
    'NonOperatingExpenses': '営業外費用',
    'ExtraordinaryIncome': '特別利益',
    'ExtraordinaryLosses': '特別損失',
    'ComprehensiveIncome': '包括利益',
    'ComprehensiveIncomeAttributableToOwners': '親会社株主に係る包括利益',
    'CoreBusinessRevenue': '本業の収益（業種別の代表科目）',
    'ResearchAndDevelopmentInSGA': '販管費に含まれる研究開発費',
    'CapitalExpendituresReported': '設備投資額（本文の記載）',
    'BookValuePerShare': '1 株当たり純資産',
    'DividendPerShare': '1 株当たり配当',
    'InterimDividendPerShare': '1 株当たり中間配当',
    'PayoutRatio': '配当性向（比率）',
    'ReturnOnEquity': '自己資本利益率（比率）',
    'EquityRatio': '自己資本比率（比率）',
    'PriceEarningsRatioAsReported': '株価収益率（有報の期末時点の記載値）',
    'TotalShareholderReturn': '株主総利回り（比率）',
    'NumberOfEmployees': '従業員数',
    'TemporaryWorkers': '臨時従業員数',
    'Deposits': '預金（銀行）',
    'Loans': '貸出金（銀行）',
    'SecuritiesBalance': '有価証券（銀行）',
    'FeesAndCommissionsIncome': '役務取引等収益（銀行）',
    'TrustFees': '信託報酬（信託）',
    'TrustAssets': '信託財産（信託）',
    'InsurancePremiums': '保険料（保険）',
    'NetPremiumsWritten': '正味収入保険料（保険）',
    'PolicyReserves': '責任準備金（保険）',
    'OutstandingClaimsReserve': '支払備金（保険）',
    'InvestmentIncome': '資産運用収益（保険）',
}

# 投資信託の財務キー（＋α）: キー → fund_document_metrics の指標
FUND_KEYS = {
    'FundCallLoans': 'fnd_call_loans',
    'FundDividends': 'fnd_dividends',
    'FundDividendsIncome': 'fnd_dividends_income',
    'FundFxPl': 'fnd_fx_pl',
    'FundInterestExpenses': 'fnd_interest_expenses',
    'FundInterestIncome': 'fnd_interest_income',
    'FundManagementFee': 'fnd_management_fee',
    'FundNavPerUnit': 'fnd_nav_per_unit',
    'FundNetAssets': 'fnd_net_assets',
    'FundOperatingExpenses': 'fnd_operating_expenses',
    'FundOperatingIncome': 'fnd_operating_income',
    'FundOperatingRevenue': 'fnd_operating_revenue',
    'FundOrdinaryIncome': 'fnd_ordinary_income',
    'FundOtherExpenses': 'fnd_other_expenses',
    'FundParentTrustSecurities': 'fnd_parent_trust_securities',
    'FundPrincipal': 'fnd_principal',
    'FundPrincipalAndOther': 'fnd_principal_and_other',
    'FundProfitLoss': 'fnd_profit_loss',
    'FundReserveForDistribution': 'fnd_reserve_for_distribution',
    'FundSurplus': 'fnd_surplus',
    'FundTotalAssets': 'fnd_total_assets',
    'FundTotalLiabilities': 'fnd_total_liabilities',
    'FundTradingPl': 'fnd_trading_pl',
    'FundTrusteeFee': 'fnd_trustee_fee',
    'FundUnpaidDividends': 'fnd_unpaid_dividends',
}
